networks:
  web:
    external: true

secrets:
  smtp-submit-password:
    file: $HOME/secrets/smtp-submit-password

services:
  smtp:
    image: juanluisbaptiste/postfix:1
    env_file:
    - host.env
    - postfix.env
    environment:
      SMTP_PASSWORD_FILE: /run/secrets/smtp-submit-password
    networks:
    - web
    restart: unless-stopped
    secrets:
    - smtp-submit-password
