networks:
  web:
    external: true
  local_db:
    external: false
  local_valkey:
    external: false

services:
  outline:
    image: outlinewiki/outline:0.84.0
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_healthy
    env_file:
    - host.env
    - outline.env
    - ../../secrets/outline.env
    networks:
    - local_db
    - local_valkey
    - web
    restart: unless-stopped
    user: root
    volumes:
    - ./data/outline:/var/lib/outline/data

  db:
    image: postgres:18
    environment:
    - POSTGRES_USER=outline
    - POSTGRES_PASSWORD=outline
    - POSTGRES_DB=outline
    healthcheck:
      test: "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 2s
    networks:
    - local_db
    restart: unless-stopped
    volumes:
    - ./data/postgres18:/var/lib/postgresql

  valkey:
    image: valkey/valkey:9
    healthcheck:
      test: ["CMD-SHELL", "[ \"$(valkey-cli ping)\" = \"PONG\" ]"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 2s
    networks:
    - local_valkey
    restart: unless-stopped
