- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    gid: 200
    state: present
  register: docker_group

- name: "Ensure {{ deploy_user }} user is in the docker group"
  ansible.builtin.user:
    user: "{{ deploy_user }}"
    groups: docker
    append: true
  when:
  - not ansible_check_mode
  - not docker_group.changed

- name: Ensure legacy Docker apt_repository file is removed
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/download_docker_com_linux_debian.list
    state: absent

- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755
    owner: root
    group: root
  register: apt_keyring_dir

- name: Ensure Docker apt GPG ASCII key is present
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644
  when:
  - not (ansible_check_mode and apt_keyring_dir.changed)
  register: apt_docker_key_asc

- name: Ensure Docker apt GPG key is dearmored
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
    creates: /etc/apt/keyrings/docker.gpg
  when:
  - not ansible_check_mode
  - not apt_keyring_dir.changed

- name: Ensure Docker apt repository is installed
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: /etc/apt/keyrings/docker.gpg
    state: present
    install_python_debian: true
  register: apt_docker_repo
  ignore_errors: '{{ ansible_check_mode }}'

- name: Ensure Docker is installed
  ansible.builtin.apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - docker-buildx-plugin
    - docker-compose-plugin
    state: present
    update_cache: true
    cache_valid_time: "{{ 0 if apt_docker_repo.changed else 600 }}"
  register: apt_docker_packages
  failed_when: not ansible_check_mode and apt_docker_packages.failed

- name: "Ensure amd64 emulation is available on arm64"
  ansible.builtin.apt:
    name:
    - qemu-user-static
    - binfmt-support
    state: present
    update_cache: yes
    cache_valid_time: 600
  when: ansible_facts["architecture"] == "aarch64"
