- name: Provision homelab host
  hosts: all
  roles:
  - users
  - packages
  - system
  - docker
  - deploy_user
  - {name: apps, become_user: '{{ deploy_user }}', when: 
      deploy_user_info.exists}
  - {name: helmet, when: '"onprem" in group_names'}
  become: true
