- name: Provision homelab host
  hosts: all
  roles:
  - system
  - auth
  - deploy_user
  - crypt_root
  - docker
  - mta
  - packages
  - users
  - name: apps
    become_user: "{{ deploy_user }}"
  - name: helmet
    when: '"onprem" in group_names'
  become: true
