- name: Provision homelab host
  hosts: all
  roles:
  - system
  - auth
  - deploy_user
  - crypt_root
  - docker
  - mta
  - packages
  - users
  - name: helmet
    when: helmet_role|d(false)
  become: true
  become_user: root
  become_method: sudo

- import_playbook: apps.yml
