x-common-service: &common-service
  networks:
  - web
  restart: unless-stopped

networks:
  web:
    external: true

secrets:
  smtp-submit-password:
    file: ../../secrets/smtp-submit-password

volumes:
  tls_certs:
    external: true

services:
  smtp:
    <<: *common-service
    build: postfix
    env_file:
    - host.env
    - postfix.env
    ports:
    - 25:25
    - 587:587
    secrets:
    - smtp-submit-password
    volumes:
    - tls_certs:/data/certs
    - ../../volumes/${COMPOSE_PROJECT_NAME}/postfix/lib:/var/lib/postfix:rw
    - ../../volumes/${COMPOSE_PROJECT_NAME}/postfix/spool:/var/spool/postfix:rw
    - ../../volumes/${COMPOSE_PROJECT_NAME}/postfix/mail:/var/mail:rw
    - ../../volumes/${COMPOSE_PROJECT_NAME}/postfix/dkim:/etc/opendkim/keys:rw
