networks:
  web:
    external: true

secrets:
  smtp-submit-password:
    file: ../../secrets/smtp-submit-password

volumes:
  tls_certs:
    driver: local

services:
  smtp:
    image: ghcr.io/smkent/homelab/postfix:latest
    # build: ../../images/postfix
    env_file:
    - host.env
    - postfix.env
    - ../../secrets/caddy.env
    networks:
    - web
    ports:
    - 25:25
    - 587:587
    restart: unless-stopped
    secrets:
    - smtp-submit-password
    volumes:
    - tls_certs:/data/certs
    - ../../volumes/${COMPOSE_PROJECT_NAME}/postfix/lib:/var/lib/postfix:rw
    - ../../volumes/${COMPOSE_PROJECT_NAME}/postfix/spool:/var/spool/postfix:rw
    - ../../volumes/${COMPOSE_PROJECT_NAME}/postfix/mail:/var/mail:rw
    - ../../volumes/${COMPOSE_PROJECT_NAME}/postfix/dkim:/etc/opendkim/keys:rw
