- name: Remove existing Dropbear ED25519 host key for conversion
  ansible.builtin.file:
    path: /etc/dropbear-initramfs/dropbear_ed25519_host_key
    state: absent

- name: Copy ED25519 host key for Dropbear
  ansible.builtin.command: dropbearconvert openssh dropbear /etc/ssh/ssh_host_ed25519_key /etc/dropbear-initramfs/dropbear_ed25519_host_key

- name: Rebuild initramfs
  ansible.builtin.command: update-initramfs -u
