networks:
  web:
    external: true
  local:
    external: false

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.9.2
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1024M
    env_file:
    - host.env
    - mealie.env
    - $HOME/secrets/mealie.env
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      DB_ENGINE: postgres
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_DB: mealie
    networks:
    - web
    - local
    restart: unless-stopped
    volumes:
    - ./data/mealie:/app/data/

  db:
    image: postgres:17
    environment:
    - POSTGRES_USER=mealie
    - POSTGRES_PASSWORD=mealie
    - POSTGRES_DB=mealie
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mealie -U mealie"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 2s
    networks:
    - local
    restart: unless-stopped
    volumes:
    - ./data/db:/var/lib/postgresql/data
