secrets:
  nut-upsd-password:
    file: ../../secrets/nut-upsd-password

services:
  nut:
    build: ../../images/nut
    env_file:
    - host.env
    - nut.env
    environment:
    privileged: true
    profiles:
    - manual
    restart: unless-stopped
    secrets:
    - nut-upsd-password
