networks:
  default:
    name: gateway_default
    external: true

services:
  nfs:
    build: nfs
    ports:
    - 2049:2049
    privileged: true
    restart: unless-stopped
    volumes:
    - ${FS_HOME_PATH-/data}:/export/data

  samba:
    image: servercontainers/samba:a3.15.4-s4.15.5-r0
    env_file:
    - samba.env
    - $HOME/secrets/samba.env
    ports:
    - 445:445
    restart: unless-stopped
    volumes:
    - ${FS_HOME_PATH-/data}:/shares/homes
    - ${FS_MEDIA_PATH-/data/media}:/shares/media
