- name: Ensure apt packages are installed
  ansible.builtin.apt:
    pkg:
    - curl
    - gnupg
    - htop
    - jq
    - libpam-modules
    - make
    - mdadm
    - mtools
    - net-tools
    - python3-pip
    - python3-venv
    - rsync
    - s3cmd
    - tmux
    - universal-ctags
    - vim-nox
    state: present
    update_cache: true
    cache_valid_time: 600
