all:
  children:
    cloud:
      hosts:
        io:
          host_public: "{{ host_suffix }}"
          linode_name: "io.net"
    onprem:
      hosts:
        ganymede:
          helmet_role: true
  vars:
    host_suffix: "{{ fqdn }}"
    ansible_host: "{{ inventory_hostname }}.{{ host_suffix }}"
