all:
  children:
    cloud:
      hosts:
        io:
    onprem:
      hosts:
        ganymede:
          helmet_role: true
  vars:
    host_suffix: "{{ fqdn }}"
    ansible_host: "{{ inventory_hostname }}.{{ host_suffix }}"
