secrets:
  backup-apps-ssh-key:
    file: ../../secrets/backup-apps-ssh-key

services:
  backup-apps:
    build: build
    env_file:
    - host.env
    - backup-apps.env
    - ../../secrets/backup-apps.env
    restart: unless-stopped
    secrets:
    - backup-apps-ssh-key
    volumes:
    - /data/backup:/data/backup:rw
