x-common-service: &common-service
  restart: unless-stopped

networks:
  web:
    external: true

services:
  caddy:
    <<: *common-service
    build: caddy
    env_file:
    - host.env
    - $HOME/secrets/caddy.env
    networks:
    - web
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./caddy/conf:/etc/caddy:ro
    - ./data/caddy_data:/data
    - ./data/caddy_config:/config

  cert-sync:
    <<: *common-service
    build: cert-sync
    depends_on:
    - caddy
    networks: []
    volumes:
    - ./data/caddy_data:/data/caddy:ro
    - ./data/certs:/data/certs
