networks:
  web:
    external: true

volumes:
  caddy_socket:
    driver: local
    name: caddy_socket

services:
  caddy:
    build: caddy
    env_file:
    - host.env
    - ../../secrets/caddy.env
    environment:
      CADDY_ADMIN: "unix//opt/caddy/caddy_admin.socket"
    networks:
    - web
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - caddy_socket:/opt/caddy
    - ./caddy:/etc/caddy:ro
    - ./host:/etc/caddy/host:ro
    - ../../volumes/${COMPOSE_PROJECT_NAME}/caddy_data:/data
    - ../../volumes/${COMPOSE_PROJECT_NAME}/caddy_config:/config
