all:
  children:
    cloud:
      hosts:
        sandbox:
          host_public: "{{ host_suffix }}"
  vars:
    host_suffix: "{{ fqdn }}"
    ansible_host: "{{ inventory_hostname }}.{{ host_suffix }}"
