services:
  cups:
    build: ../../images/cups
    platform: linux/amd64
    ports:
    - 631:631
    restart: unless-stopped
    volumes:
    - ../../volumes/${COMPOSE_PROJECT_NAME}/cups:/data/cups:rw
