name: Containers

env:
  IMAGE_PREFIX: homelab

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  discover:
    name: "Discover builds"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: ğŸ’¾ Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: ğŸ”­ Discover container images to build
      id: set-matrix
      run: |
        set -x
        base_ref="${{ github.event.before }}"
        head_ref="${{ github.event.after }}"
        if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
          base_ref="${{ github.event.pull_request.base.sha }}"
          head_ref="${{ github.event.pull_request.head.sha }}"
        fi
        if git diff --name-only "${base_ref}" "${head_ref}" | grep -q "^\.github/workflows"; then
          changed_dirs="$(git ls-files | grep "^compose/images/.*/Dockerfile$" | sort -u)"
        else
          changed_dirs="$(git diff --name-only "${base_ref}" "${head_ref}" | grep "^compose/images/.*/Dockerfile$" | sort -u)"
        fi
        if [ -n "${changed_dirs}" ]; then
          json="$(printf '%s\n' "$(echo "${changed_dirs}" | xargs -n1 dirname | xargs -n1 basename)" | jq -R . | jq -s -c .)"
        else
          json="[]";
        fi
        echo "matrix={\"image\":${json}}" >> "${GITHUB_OUTPUT}"

  build:
    name: "Build and push / ${{ matrix.image }}"
    needs: discover
    if: ${{ fromJson(needs.discover.outputs.matrix).image[0] != null }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}

    steps:
    - name: ğŸ’¾ Check out repository
      uses: actions/checkout@v4

    - name: âš™ï¸  Set up qemu
      uses: docker/setup-qemu-action@v3

    - name: ğŸ› ï¸ Set up buildx
      uses: docker/setup-buildx-action@v3

    - name: ğŸ”‘ Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: ğŸ“¡ Collect image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_PREFIX }}/${{ matrix.image }}
        tags: |
          type=raw,value=latest,enable={{ is_default_branch }}
          type=ref,event=branch
          type=ref,event=pr
        labels: |
          org.opencontainers.image.source=${{ github.repository_url }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.title=homelab image for ${{ matrix.image }}
          org.opencontainers.image.description=customized homelab image for ${{ matrix.image }}
          org.opencontainers.image.licenses=

    - name: ğŸ“¦ Build and publish container image
      uses: docker/build-push-action@v5
      with:
        context: ./compose/images/${{ matrix.image }}
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
