name: Docker

env:
  IMAGE_PREFIX: homelab

on:
  push:
  workflow_dispatch:

jobs:
  discover:
    name: "Discover builds"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: ğŸ’¾ Check out repository
    - uses: actions/checkout@v4

    - name: ğŸ”­ Discover container images to build
    - id: set-matrix
      run: |
        dirs="$(find compose/images -mindepth 1 -maxdepth 1 -type d -exec test -f "{}/Dockerfile" \; -print | xargs -n1 basename | sort)"
        json="$(printf '%s\n' "${dirs}" | jq -R . | jq -s -c .)"
        echo "matrix={\"image\":${json}}" >> "${GITHUB_OUTPUT}"

  build:
    name: "Build and push / ${{ matrix.image }}"
    needs: discover
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}

    steps:
    - name: ğŸ’¾ Check out repository
    - uses: actions/checkout@v4

    - name: âš™ï¸  Set up qemu
    - uses: docker/setup-qemu-action@v3

    - name: ğŸ› ï¸ Set up buildx
    - uses: docker/setup-buildx-action@v3

    - name: ğŸ”‘ Log in to the container registry
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: ğŸ“¦ Build and publish container image
    - uses: docker/build-push-action@v5
      with:
        context: ./compose/images/${{ matrix.image }}
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_PREFIX }}/${{ matrix.image }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
